[package]
name = "RustEmbedBot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
regex = "1.10.6"
url = "2.5.4"
reqwest = "0.12.9"
serenity = "0.12.2"
tokio = { version = "1", features = ["full"] }
uuid = {version = "1.10.0", features = ["v4"]}
