name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build linux
      run: |
        cargo build --release --target x86_64-unknown-linux-gnu
        cd target/x86_64-unknown-linux-gnu
        ls
        gh release upload ${{github.event.release.tag_name}} RustEmbedBot
      env:
        GITHUB_TOKEN: ${{github.TOKEN}}
      shell: bash
